### ISSUE TITLE
Filter sensors by Smart Meter or not

### ISSUE THREAD

**Issue by GuyKh** [GuyKh/bezeq-energy-custom-component#13]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/GuyKh/bezeq-energy-custom-component/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Don't show irrelevant sensors for non-smart elec meters

### Describe the solution you'd like

Filtering

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by GuyKh** [comment]
```
bezeq_energy data
Traceback (most recent call last):
File "/config/custom_components/bezeq_energy/coordinator.py", line 132, in _get_data
data[MONTHLY_USED_KEY] = _get_card_by_service_type(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 49, in _get_card_by_service_type
card = next(filter(lambda card: card.service_type == service_type, cards))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 173, in _async_update_data
return await self._get_data()
^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine raised StopIteration
2024-10-29 15:13:03.809 ERROR (MainThread) [custom_components.bezeq_energy] Unexpected error fetching bezeq_energy data
Traceback (most recent call last):
File "/config/custom_components/bezeq_energy/coordinator.py", line 132, in _get_data
data[MONTHLY_USED_KEY] = _get_card_by_service_type(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 49, in _get_card_by_service_type
card = next(filter(lambda card: card.service_type == service_type, cards))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 173, in _async_update_data
return await self._get_data()
^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine raised StopIteration
2024-10-29 15:13:18.135 ERROR (MainThread) [custom_components.bezeq_energy] Unexpected error fetching bezeq_energy data
Traceback (most recent call last):
File "/config/custom_components/bezeq_energy/coordinator.py", line 132, in _get_data
data[MONTHLY_USED_KEY] = _get_card_by_service_type(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 49, in _get_card_by_service_type
card = next(filter(lambda card: card.service_type == service_type, cards))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 173, in _async_update_data
return await self._get_data()
^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine raised StopIteration
2024-10-29 15:13:43.878 ERROR (MainThread) [custom_components.bezeq_energy] Unexpected error fetching bezeq_energy data
Traceback (most recent call last):
File "/config/custom_components/bezeq_energy/coordinator.py", line 132, in _get_data
data[MONTHLY_USED_KEY] = _get_card_by_service_type(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 49, in _get_card_by_service_type
card = next(filter(lambda card: card.service_type == service_type, cards))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/bezeq_energy/coordinator.py", line 173, in _async_update_data
return await self._get_data()
^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine raised StopIteration
```

need to filter also coordinator data
